#!/bin/bash
apt-get update
apt-get upgrade
apt-get install-y nginx
systemctl start nginx
systemctl enable nginx
apt-get install-y git
curl-sL https://deb.nodesource.com/setup_18.x | sudo-E bash
apt-get install-y nodejs
git clone https://github.com/supriyaaupadhyay/asg7.git
cd asg7
npminstall
node index.js
